name: Feeds (hourly → data/feeds.json)

on:
  schedule:
    - cron: "5 * * * *"   # every hour at :05 UTC
  workflow_dispatch:       # allows manual Run workflow

permissions:
  contents: write          # needed to commit data/feeds.json
  actions: read

concurrency:
  group: feeds-json
  cancel-in-progress: false

jobs:
  build-feeds-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build data/feeds.json
        env:
          GET_IMAGES: "true"
          MAX_PER_FEED: "20"
          MAX_TOTAL: "120"
          TZ: "Europe/London"
        run: |
          python scripts/ingest_feeds.py

      - name: Commit changes (if any)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --quiet --exit-code data/feeds.json; then
            echo "No feed changes — nothing to commit."
            exit 0
          fi
          git config user.name "tnl-bot"
          git config user.email "bot@users.noreply.github.com"
          git add data/feeds.json
          git commit -m "chore(feeds): update data/feeds.json [skip ci]"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:${{ github.ref_name }}
